image: alpine:latest

pages:
  stage: deploy
  script:
    - mkdir .public
    - cp -r SM_module/docs/build/SM/* .public
    - mv .public public
  artifacts:
    paths:
    - public
  only:
  - master


